/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_javavision_camera_LinuxCamera */

#ifndef _Included_org_javavision_camera_LinuxCamera
#define _Included_org_javavision_camera_LinuxCamera
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_javavision_camera_LinuxCamera
 * Method:    getNativeImage
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_scottsbots_core_vision_LinuxCamera_getNativeImage
  (JNIEnv *, jobject);

/*
 * Class:     org_javavision_camera_LinuxCamera
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_scottsbots_core_vision_LinuxCamera_init
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
